apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
  namespace: monitoring
data:
  config.yaml: |
    externalRules:
    - seriesQuery: 'ml_service_signal'
      resources:
        namespaced: false
      name:
        matches: "^ml_service_signal$"
        as: "ml_service_signal"
      metricsQuery: 'ml_service_signal{<<.LabelMatchers>>}'
