apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: balancit
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8000"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
        - name: service-a
          image: service-a:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_ENDPOINT
              value: "http://otel-collector.balancit:4317"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: balancit
spec:
  selector:
    app: service-a
  ports:
    - port: 8000
      targetPort: 8000
